services:
  db:
    image: ghcr.io/stac-utils/pgstac:v0.8.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: eo_user
      POSTGRES_PASSWORD: eo_password
      POSTGRES_DB: eo_platform
      PGUSER: eo_user
      PGPASSWORD: eo_password
      PGDATABASE: eo_platform
    ports:
      - "5432:5432"
    volumes:
      - ISRO:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    container_name: titiler_server
    ports:
      - "8001:80"
    environment:
      - CPL_VSIL_CURL_ALLOWED_EXTENSIONS=.tif,.jp2
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin123
      - AWS_S3_ENDPOINT=minio:9000
      - AWS_ENDPOINT_URL=http://minio:9000
      - AWS_VIRTUAL_HOSTING=FALSE
      - AWS_HTTPS=NO
    volumes:
      - ./backend/cogs:/app/cogs
      - ./backend/vista_data:/app/vista_data
    depends_on:
      - db
      - minio

  fastapi:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    environment:
      - DB_HOST=db
      - DB_USER=eo_user
      - DB_PASS=eo_password
      - DB_NAME=eo_platform
      - TITILER_URL=http://localhost:8001
      - TITILER_INTERNAL_URL=http://titiler:80
      - FASTAPI_INTERNAL_URL=http://fastapi:8000
    depends_on:
      - db
      - titiler

volumes:
  ISRO:
    external: true
  minio_data:
